// Shared data for all three concepts

const FOODS = [
  {
    id: 'orijen-original',
    brand: 'Orijen',
    name: 'Original',
    line: 'Biologically Appropriate Dry',
    score: 94,
    grade: 'A',
    price: 98,
    size: '25 lb',
    protein: 38,
    fat: 18,
    fiber: 5,
    moisture: 12,
    firstIngredient: 'Fresh chicken meat',
    ingredients: ['Fresh chicken', 'Fresh turkey', 'Fresh mackerel', 'Whole eggs', 'Red lentils', 'Green peas'],
    flags: ['Grain-free', 'No by-products', 'No artificial preservatives'],
    warnings: [],
    tagline: 'Whole-prey ratio with fresh regional meats',
    accent: 'oklch(0.62 0.14 140)',
  },
  {
    id: 'blue-buffalo-life',
    brand: 'Blue Buffalo',
    name: 'Life Protection Adult Chicken',
    line: 'Life Protection Formula',
    score: 72,
    grade: 'B',
    price: 62,
    size: '30 lb',
    protein: 24,
    fat: 14,
    fiber: 5,
    moisture: 10,
    firstIngredient: 'Deboned chicken',
    ingredients: ['Deboned chicken', 'Chicken meal', 'Brown rice', 'Barley', 'Oatmeal', 'Chicken fat'],
    flags: ['No by-products', 'Contains LifeSource bits'],
    warnings: ['Includes pea protein'],
    tagline: 'Balanced chicken & brown rice everyday diet',
    accent: 'oklch(0.62 0.14 240)',
  },
  {
    id: 'purina-pro',
    brand: 'Purina Pro Plan',
    name: 'Savor Shredded Chicken & Rice',
    line: 'Pro Plan Adult',
    score: 68,
    grade: 'B-',
    price: 54,
    size: '35 lb',
    protein: 26,
    fat: 16,
    fiber: 3,
    moisture: 12,
    firstIngredient: 'Chicken',
    ingredients: ['Chicken', 'Rice', 'Whole grain wheat', 'Poultry by-product meal', 'Corn gluten meal', 'Beef fat'],
    flags: ['Vet-recommended'],
    warnings: ['Contains by-products', 'Contains corn gluten'],
    tagline: 'Shredded texture, high-protein classic',
    accent: 'oklch(0.62 0.14 60)',
  },
  {
    id: 'rams',
    brand: 'Rams',
    name: 'Lamb & Sweet Potato',
    line: 'Single Protein Recipe',
    score: 81,
    grade: 'A-',
    price: 72,
    size: '22 lb',
    protein: 28,
    fat: 15,
    fiber: 4,
    moisture: 10,
    firstIngredient: 'Fresh lamb',
    ingredients: ['Fresh lamb', 'Lamb meal', 'Sweet potato', 'Chickpeas', 'Lamb fat', 'Flaxseed'],
    flags: ['Grain-free', 'Single protein', 'Small-batch'],
    warnings: [],
    tagline: 'Limited-ingredient single-protein recipe',
    accent: 'oklch(0.62 0.14 30)',
  },
  {
    id: 'acana-heritage',
    brand: 'Acana',
    name: 'Heritage Free-Run Poultry',
    line: 'Heritage',
    score: 89,
    grade: 'A',
    price: 84,
    size: '25 lb',
    protein: 31,
    fat: 17,
    fiber: 5,
    moisture: 12,
    firstIngredient: 'Deboned chicken',
    ingredients: ['Deboned chicken', 'Chicken meal', 'Turkey meal', 'Whole red lentils', 'Whole green peas'],
    flags: ['Grain-free', 'Free-run poultry'],
    warnings: [],
    tagline: 'Free-run poultry, whole-prey ratios',
    accent: 'oklch(0.62 0.14 160)',
  },
  {
    id: 'hills-science',
    brand: 'Hill\u2019s Science Diet',
    name: 'Adult Chicken & Barley',
    line: 'Science Diet Adult',
    score: 65,
    grade: 'C+',
    price: 58,
    size: '30 lb',
    protein: 20,
    fat: 14,
    fiber: 3,
    moisture: 10,
    firstIngredient: 'Chicken',
    ingredients: ['Chicken', 'Cracked pearled barley', 'Whole grain wheat', 'Corn gluten meal', 'Chicken meal'],
    flags: ['Vet-recommended'],
    warnings: ['Contains corn gluten', 'Lower protein %'],
    tagline: 'Clinically proven antioxidant blend',
    accent: 'oklch(0.62 0.14 300)',
  },
  {
    id: 'taste-wild',
    brand: 'Taste of the Wild',
    name: 'High Prairie',
    line: 'Grain-Free Recipe',
    score: 83,
    grade: 'A-',
    price: 59,
    size: '28 lb',
    protein: 32,
    fat: 18,
    fiber: 4,
    moisture: 10,
    firstIngredient: 'Water buffalo',
    ingredients: ['Water buffalo', 'Lamb meal', 'Chicken meal', 'Sweet potatoes', 'Peas', 'Potatoes'],
    flags: ['Grain-free', 'Novel proteins'],
    warnings: [],
    tagline: 'Roasted bison & venison blend',
    accent: 'oklch(0.62 0.14 80)',
  },
  {
    id: 'wellness-core',
    brand: 'Wellness CORE',
    name: 'Original Chicken & Turkey',
    line: 'CORE Grain-Free',
    score: 86,
    grade: 'A',
    price: 76,
    size: '26 lb',
    protein: 34,
    fat: 16,
    fiber: 4,
    moisture: 10,
    firstIngredient: 'Deboned chicken',
    ingredients: ['Deboned chicken', 'Chicken meal', 'Turkey meal', 'Peas', 'Dried ground potatoes'],
    flags: ['Grain-free', 'High-protein'],
    warnings: [],
    tagline: 'Protein-focused grain-free formula',
    accent: 'oklch(0.62 0.14 200)',
  },
];

const SCORE_FACTORS = [
  { label: 'Ingredient quality', weight: 35 },
  { label: 'Protein sources', weight: 25 },
  { label: 'Guaranteed analysis', weight: 20 },
  { label: 'Recall history', weight: 10 },
  { label: 'Transparency', weight: 10 },
];

const STATS = {
  foods: 1042,
  brands: 187,
  updatedAgo: '3 days ago',
};

Object.assign(window, { FOODS, SCORE_FACTORS, STATS });
