'use client';
import { useState, useRef, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import SearchBox from '@/app/components/SearchBox';
import CompareBubble from '@/app/components/CompareBubble';
import SignUpButton from '@/app/components/SignUpButton';
import RecallsNav from '@/app/components/RecallsNav';

const CATEGORIES = [
  {
    label: 'Our Data & Scoring',
    questions: [
      {
        q: 'Where does GoodKibble get its data?',
        a: "Every product in our database is sourced directly from the manufacturer's own website — the guaranteed analysis, ingredient list, and nutritional information printed on the label. We don't pull data from third-party retailers, user submissions, or AI-generated estimates. If the manufacturer publishes it, that's what we use. If they don't, we don't guess.",
      },
      {
        q: 'How does the GoodKibble Score work?',
        a: "Every dry kibble is scored 0\u2013100 across eight categories. The first four measure nutritional content from the guaranteed analysis (Protein, Fat, Carbohydrates, and Fiber). The last four evaluate ingredient quality from the ingredient list (Protein Sources, Preservatives, Additives, and Functional Ingredients). Each category has specific thresholds informed by AAFCO standards, NRC guidelines, and peer-reviewed veterinary research. We convert all nutritional values to a dry-matter basis so every product is compared on equal footing.",
        link: { text: 'Read our full scoring methodology \u2192', href: '/how-we-score' },
      },
      {
        q: 'What do the score ranges mean?',
        a: "90\u2013100 is Excellent (exceeds standards across all categories), 80\u201389 is Great (strong profile with minor gaps), 70\u201379 is Good (meets AAFCO standards with favorable ingredients), 60\u201369 is Fair (meets minimums, room for improvement), and below 60 is Poor (notable concerns or below AAFCO minimums). These ranges are a comparative ranking, not a clinical recommendation.",
      },
      {
        q: 'How often does the scoring algorithm change?',
        a: "Veterinary nutrition is an evolving field, and our methodology evolves with it. We review scoring thresholds whenever relevant new peer-reviewed research is published. When we do update, every product in our database is rescored under the new version so all scores remain directly comparable. We document every change in our version history.",
        link: { text: 'See version history \u2192', href: '/how-we-score' },
      },
      {
        q: "Why does my dog's prescription food score low?",
        a: "Prescription and veterinary diets are formulated for specific medical purposes \u2014 kidney disease, allergies, pancreatitis, weight management, etc. These foods intentionally adjust nutrient levels in ways that may score lower on a general-nutrition scale. A low GoodKibble Score on a prescription diet doesn't mean it's bad \u2014 it means it's specialized. Always follow your veterinarian's dietary recommendations.",
      },
      {
        q: 'Do you only score dry kibble?',
        a: "Currently, yes. The GoodKibble Score is calibrated for dry kibble only. Wet food, raw food, freeze-dried, and dehydrated formats have different nutritional profiles and moisture levels that require separate scoring frameworks. We may expand to other formats in the future.",
      },
    ],
  },
  {
    label: 'Independence & Money',
    questions: [
      {
        q: 'Does GoodKibble accept money from dog food brands?',
        a: "No. We do not accept payments, free products, sponsorships, or any form of compensation from pet food manufacturers or brands. No company can pay to influence their score, boost their ranking, or get preferential treatment. Scores are generated by the algorithm \u2014 not by business relationships.",
      },
      {
        q: 'How does GoodKibble make money?',
        a: "Two ways. First, we offer GoodKibble Pro \u2014 a paid subscription that unlocks additional features and tools. Second, we participate in the Amazon Associates affiliate program. When you click a purchase link and buy through Amazon, we may earn a small commission at no extra cost to you. Neither Pro subscriptions nor affiliate relationships have any influence on scores.",
      },
    ],
  },
  {
    label: 'Features & Tools',
    questions: [
      {
        q: 'How does the Ingredient Analyzer work?',
        a: "The Ingredient Analyzer breaks down a product's full ingredient list and flags items of interest \u2014 artificial preservatives, controversial additives, unnamed protein sources, and beneficial functional ingredients. It also detects patterns like ingredient splitting. Everything is based on the ingredient list as printed on the label.",
      },
      {
        q: 'How does the recall page work?',
        a: "Our recall tracker monitors FDA and manufacturer-reported recall notices for dog food products. You can check whether any product has been subject to a recall, see the date and reason, and filter by brand. Recall history is tracked separately and is not factored into the GoodKibble Score.",
      },
      {
        q: 'How do I create an account and save foods?',
        a: "Sign up with your email from any product page or the top navigation. Once you have an account, you can create a profile for your dog and save foods for easy comparison. This lets you track what you've tried, compare options side by side, and get a personalized view.",
      },
      {
        q: 'Can I compare two dog foods side by side?',
        a: "Yes. Use the Compare feature from the top navigation or any product page to put two or more foods next to each other. You'll see a full breakdown across all eight scoring categories, nutritional values on a dry-matter basis, and ingredient differences highlighted.",
      },
    ],
  },
  {
    label: 'General',
    questions: [
      {
        q: 'Is GoodKibble veterinary advice?',
        a: "No. GoodKibble is an informational tool, not a veterinary service. Nothing on this site constitutes veterinary advice, diagnosis, or treatment. The GoodKibble Score is a comparative ranking based on publicly available label data. Always consult a licensed veterinarian before making dietary decisions for your pet.",
      },
      {
        q: 'How many products does GoodKibble cover?',
        a: "We currently have over 1,000 scored products across dozens of major and specialty brands, with new products added regularly. Our goal is to cover every dry kibble available in the U.S. market. If you can't find a specific product, use the form below and we'll work on adding it.",
      },
      {
        q: 'I found an error in a product\'s data. How do I report it?',
        a: "We take data accuracy seriously. If you spot something that doesn't match what's on the manufacturer's website \u2014 a wrong protein percentage, a missing ingredient, a mislabeled flavor \u2014 use the form below to let us know. Include the product name and what looks off, and we'll investigate and correct it.",
      },
      {
        q: 'Do you have an app?',
        a: "Not yet, but GoodKibble is fully responsive and works great on mobile browsers. You can add GoodKibble to your phone's home screen for quick access \u2014 it works just like an app.",
      },
    ],
  },
];

function AccordionItem({ q, a, link, isOpen, onToggle }) {
  const contentRef = useRef(null);
  const [height, setHeight] = useState(0);

  useEffect(() => {
    if (isOpen && contentRef.current) {
      setHeight(contentRef.current.scrollHeight);
    } else {
      setHeight(0);
    }
  }, [isOpen]);

  return (
    <div style={{ borderBottom: '1px solid #f0ebe3' }}>
      <button onClick={onToggle} style={{
        width: '100%', display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '18px 0', border: 'none', background: 'none', cursor: 'pointer',
        textAlign: 'left', fontFamily: "'Inter', sans-serif",
      }}>
        <span style={{ fontSize: 15, fontWeight: 600, color: '#1a1612', flex: 1, paddingRight: 16 }}>{q}</span>
        <span style={{
          fontSize: 14, color: '#b5aa99', transition: 'transform 0.25s ease',
          transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)', flexShrink: 0,
        }}>{'\u25BC'}</span>
      </button>
      <div style={{
        height, overflow: 'hidden', transition: 'height 0.25s ease',
      }}>
        <div ref={contentRef} style={{ paddingBottom: 18 }}>
          <p style={{ fontSize: 14, color: '#5a5248', lineHeight: 1.7, fontFamily: "'Inter', sans-serif" }}>{a}</p>
          {link && (
            <a href={link.href} style={{
              display: 'inline-block', marginTop: 8, fontSize: 13, color: '#C68A1B',
              fontWeight: 600, textDecoration: 'none', fontFamily: "'Inter', sans-serif",
            }}>{link.text}</a>
          )}
        </div>
      </div>
    </div>
  );
}

function FoodRequestForm() {
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [status, setStatus] = useState(null); // null | 'sending' | 'success' | 'error'

  async function handleSubmit(e) {
    e.preventDefault();
    if (!email.trim() || !message.trim()) return;
    setStatus('sending');
    try {
      const res = await fetch('/api/food-request', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email: email.trim(), message: message.trim() }),
      });
      if (res.ok) setStatus('success');
      else setStatus('error');
    } catch {
      setStatus('error');
    }
  }

  if (status === 'success') {
    return (
      <div style={{
        background: '#fff', borderRadius: 20, border: '1px solid #ede8df',
        padding: 32, textAlign: 'center',
      }}>
        <div style={{ fontSize: 32, marginBottom: 12 }}>{'\u2705'}</div>
        <div style={{ fontSize: 16, fontWeight: 600, color: '#1a1612', marginBottom: 6, fontFamily: "'Inter', sans-serif" }}>
          Got it — we'll look into it.
        </div>
        <div style={{ fontSize: 14, color: '#8a7e72', fontFamily: "'Inter', sans-serif" }}>
          We'll email you when the product is added.
        </div>
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit} style={{
      background: '#fff', borderRadius: 20, border: '1px solid #ede8df', padding: 32,
    }}>
      <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', color: '#C68A1B', marginBottom: 8, fontFamily: "'Inter', sans-serif" }}>Request</div>
      <h2 style={{ fontFamily: "'Instrument Serif', serif", fontSize: 22, fontWeight: 700, color: '#1a1612', marginBottom: 6 }}>
        Can't find your dog's food?
      </h2>
      <p style={{ fontSize: 14, color: '#8a7e72', lineHeight: 1.6, marginBottom: 20, fontFamily: "'Inter', sans-serif" }}>
        Tell us what you're looking for. We'll add it to our queue and notify you when it's on the site.
      </p>
      <input
        type="email" value={email} onChange={e => setEmail(e.target.value)}
        placeholder="Your email"
        required
        style={{
          width: '100%', padding: '12px 16px', borderRadius: 12, border: '1.5px solid #ede8df',
          fontSize: 14, fontFamily: "'Inter', sans-serif", background: '#faf8f5',
          outline: 'none', color: '#1a1612', marginBottom: 12, boxSizing: 'border-box',
        }}
        onFocus={e => e.target.style.borderColor = '#C68A1B'}
        onBlur={e => e.target.style.borderColor = '#ede8df'}
      />
      <textarea
        value={message} onChange={e => setMessage(e.target.value)}
        placeholder="What food are you looking for? (brand, product name, flavor — whatever you know)"
        required
        rows={3}
        style={{
          width: '100%', padding: '12px 16px', borderRadius: 12, border: '1.5px solid #ede8df',
          fontSize: 14, fontFamily: "'Inter', sans-serif", background: '#faf8f5',
          outline: 'none', color: '#1a1612', marginBottom: 16, resize: 'vertical',
          boxSizing: 'border-box',
        }}
        onFocus={e => e.target.style.borderColor = '#C68A1B'}
        onBlur={e => e.target.style.borderColor = '#ede8df'}
      />
      {status === 'error' && (
        <div style={{ fontSize: 13, color: '#b5483a', marginBottom: 12, fontFamily: "'Inter', sans-serif" }}>
          Something went wrong. Please try again.
        </div>
      )}
      <button type="submit" disabled={!email.trim() || !message.trim() || status === 'sending'} style={{
        padding: '12px 28px', borderRadius: 100, background: '#1a1612', color: '#faf8f4',
        fontSize: 14, fontWeight: 600, border: 'none', cursor: 'pointer',
        fontFamily: "'Inter', sans-serif", opacity: (!email.trim() || !message.trim() || status === 'sending') ? 0.5 : 1,
        transition: 'opacity 0.2s',
      }}>
        {status === 'sending' ? 'Sending...' : 'Let us know \u2192'}
      </button>
    </form>
  );
}

export default function FAQPage() {
  const router = useRouter();
  const goHome = () => router.push('/');
  const [openItems, setOpenItems] = useState({});

  function toggleItem(catIdx, qIdx) {
    setOpenItems(prev => {
      const key = `${catIdx}-${qIdx}`;
      const currentOpen = prev[catIdx];
      if (currentOpen === qIdx) return { ...prev, [catIdx]: null };
      return { ...prev, [catIdx]: qIdx };
    });
  }

  return (
    <div style={{ minHeight: '100vh', background: '#faf8f5' }}>
      <nav className="nav-bar" style={{
        padding: '16px 24px 16px 40px', display: 'flex', justifyContent: 'space-between',
        alignItems: 'center', borderBottom: '1px solid #ede8df', background: '#faf8f5',
        position: 'sticky', top: 0, zIndex: 40, gap: 16,
      }}>
        <div onClick={goHome} style={{
          fontFamily: "'Instrument Serif', serif", fontSize: 32, fontWeight: 800,
          color: '#1a1612', cursor: 'pointer', flexShrink: 0,
        }}>Good<span style={{ color: '#E5A93D' }}>Kibble</span></div>
        <div className="nav-search" style={{ flex: 1, maxWidth: 380 }}>
          <SearchBox onSelect={(food) => {
            if (food?.brand_slug && food?.slug) router.push(`/dog-food/${food.brand_slug}/${food.slug}`);
            else router.push(`/food/${food?.id || food}`);
          }} variant="nav" />
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <RecallsNav />
          <CompareBubble />
          <SignUpButton />
        </div>
      </nav>

      <div style={{ maxWidth: 740, margin: '0 auto', padding: '48px 24px 80px' }}>
        <p style={{ fontSize: 12, fontWeight: 600, letterSpacing: 2, textTransform: 'uppercase', color: '#b5aa99', marginBottom: 8 }}>Support</p>
        <h1 style={{ fontFamily: "'Instrument Serif', serif", fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 800, color: '#1a1612', marginBottom: 8 }}>Frequently Asked Questions</h1>
        <p style={{ fontSize: 15, color: '#8a7e72', lineHeight: 1.6, marginBottom: 48, fontFamily: "'Inter', sans-serif" }}>
          Everything you need to know about how GoodKibble works, where our data comes from, and what the scores mean.
        </p>

        {CATEGORIES.map((cat, catIdx) => (
          <div key={catIdx} style={{ marginBottom: 40 }}>
            <div style={{
              fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase',
              color: '#C68A1B', marginBottom: 16, fontFamily: "'Inter', sans-serif",
            }}>{cat.label}</div>
            <div style={{ background: '#fff', borderRadius: 16, border: '1px solid #ede8df', padding: '0 24px' }}>
              {cat.questions.map((item, qIdx) => (
                <AccordionItem
                  key={qIdx}
                  q={item.q}
                  a={item.a}
                  link={item.link}
                  isOpen={openItems[catIdx] === qIdx}
                  onToggle={() => toggleItem(catIdx, qIdx)}
                />
              ))}
            </div>
          </div>
        ))}

        <div style={{ marginTop: 56 }}>
          <FoodRequestForm />
        </div>
      </div>

      {/* Footer */}
      <div className="footer-bar" style={{
        borderTop: '1px solid #ede8df', padding: '32px 40px',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        flexWrap: 'wrap', gap: 12,
      }}>
        <div style={{ fontFamily: "'Instrument Serif', serif", fontSize: 32, fontWeight: 800, color: '#1a1612' }}>
          Good<span style={{ color: '#E5A93D' }}>Kibble</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16, fontSize: 13, color: '#b5aa99', flexWrap: 'wrap' }}>
          <a href="/terms" style={{ color: '#b5aa99', textDecoration: 'none' }}>Terms</a>
          <a href="/privacy" style={{ color: '#b5aa99', textDecoration: 'none' }}>Privacy</a>
          <a href="/recalls" style={{ color: '#b5aa99', textDecoration: 'none' }}>Recalls</a>
          <a href="/faq" style={{ color: '#b5aa99', textDecoration: 'none' }}>FAQ</a>
          <span>&copy; 2026 GoodKibble. Not affiliated with any dog food brand.</span>
        </div>
      </div>
    </div>
  );
}
